### Installing Numpy
* conda install numpy
*   pip install numpy

In [11]:
import numpy as np

In [12]:
a=np.array([[1.5,2,0],[5,1,3]])
a

array([[1.5, 2. , 0. ],
       [5. , 1. , 3. ]])

In [13]:
a.shape

(2, 3)

In [14]:
a.ndim

2

In [15]:
a=np.array([[1.5,2],[2,3]],dtype=int)
a

array([[1, 2],
       [2, 3]])

In [16]:
type(a)

numpy.ndarray

In [17]:
np.zeros([1,3])

array([[0., 0., 0.]])

In [18]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

**Slicing**

In [19]:
a=[1,1,3,5,3,1,3,4]
a

[1, 1, 3, 5, 3, 1, 3, 4]

In [20]:
a[1:5]

[1, 3, 5, 3]

In [21]:
a=np.array(a)
a[1:5]

array([1, 3, 5, 3])

In [22]:
cc="hello, my name is Aya"
cc[-3:]

'Aya'

In [23]:
# Creating a NumPy array from a Python list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

# Basic array operations
print("Original array:", my_array)

# Accessing elements of the array
print("Element at index 0:", my_array[0])
print("Slice of the array:", my_array[1:4])

# Array operations
print("Sum of the array elements:", np.sum(my_array))
print("Mean of the array elements:", np.mean(my_array))
print("Maximum element in the array:", np.max(my_array))
print("Minimum element in the array:", np.min(my_array))


Original array: [1 2 3 4 5]
Element at index 0: 1
Slice of the array: [2 3 4]
Sum of the array elements: 15
Mean of the array elements: 3.0
Maximum element in the array: 5
Minimum element in the array: 1


**EXERCISE** In this exercise, baseball is a list of lists. The main list contains 6 elements. Each of these elements is a list containing the height and the weight of 6 baseball players, in this order. baseball is already coded for you in the script.


In [24]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2],
            [180, 90],
            [190, 95]]
# Create a 2D numpy array from baseball: np_baseball


# Print out the type of np_baseball

# Print out the shape of np_baseball

# Print out the 5th row of np_baseball

# Select the entire second column of np_baseball and name it np_weight_lb

# Print out height of 3rd player

#get maximum weight

#get mean of hights

In [25]:
x=np.array([20, 25,30, 35, 40, 45, 50, 55, 60, 65 ])
y=np.array([0.5,1.8,5,6.2,6,6.5,7.8,9.4,9.8,10.9])

In [26]:
# if x is list 

def IQR(vector_x):
    vector_x.sort()
    q2_idx = len(vector_x)//2
    q1_idx = q2_idx//2
    q3_idx = q2_idx+(len(vector_x)-q2_idx)//2
    iqr = vector_x[q3_idx] - vector_x[q1_idx]
    outliers = []
    extrem_outiers = []
    for i in range(len(vector_x)):
        
        if (vector_x[i] > vector_x[q3_idx]+iqr*1.5 and vector_x[i] <= vector_x[q3_idx] + 3*iqr) or (vector_x[i] < vector_x[q1_idx]-iqr*1.5 and vector_x[i] >= vector_x[q1_idx] - 3*iqr ):
            outliers.append(vector_x[i])
            
        if vector_x[i] > vector_x[q3_idx] + 3*iqr or vector_x[i] < vector_x[q1_idx] - 3*iqr:
            extrem_outiers.append(vector_x[i])
            
    return vector_x[q1_idx] , vector_x[q2_idx] , vector_x[q3_idx] , iqr , outliers , extrem_outiers
    

In [27]:
q1, q2, q3, iqr, outliers, extreme_outliers = IQR(x)
print("Q1:",q1)
print("Q2:",q2)
print("Q3:",q3)
print("IQR:",iqr)
print("outliers:",outliers)
print("extreme_outliers:",extreme_outliers)

Q1: 30
Q2: 45
Q3: 55
IQR: 25
outliers: []
extreme_outliers: []


In [28]:
np_baseball = np.array(baseball)

In [39]:
import numpy as np

In [40]:
np_baseball = np.array(baseball)

In [41]:
print( type(np_baseball))

<class 'numpy.ndarray'>


In [42]:
print( np_baseball.shape)

(6, 2)


In [48]:
print(np_baseball[4])

[180.  90.]


In [49]:
np_weight_lb = np_baseball[:, 1]
print( np_weight_lb)

[ 78.4 102.7  98.5  75.2  90.   95. ]


In [50]:
print( np_baseball[2, 0])

210.0


In [51]:
max_weight = np_weight_lb.max()
print( max_weight)

102.7


In [47]:
mean_height = np_baseball[:, 0].mean()
print( mean_height)

193.83333333333334
